apiVersion: v1
kind: ConfigMap
metadata:
  name: patrones1-ConfigMap
  namespace: patrones1
data:
  DB_HOST: patrones1-postgres-service.patrones1.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "stringdb"