apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrones1
  namespace: patrones1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  patrones1
  template:
    metadata:
      labels:
        app:  patrones1
    spec:
      containers:
      - name: patrones1
        image: charliebello/patrones1:5.2.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: patrones1-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: patrones1-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: patrones1-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: patrones1-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: patrones1-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: patrones1-service
  namespace: patrones1
spec:
  selector:
    app:  patrones1
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patrones1-hpa
  namespace: patrones1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patrones1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80